### ISSUE TITLE
missing space

### ISSUE THREAD

**Issue by josheela** [Infragistics/convertwire#114]
docfile : 
       wingrid-determining-which-band-the-user-clicked.adoc
online link:
          http://help.infragistics.com/doc/WinForms/2015.2/?page=WinGrid_Determining_Which_Band_the_User_Clicked.html
topic: actual
         UltraGrid1.MouseMove - The code in the MouseMoveevent 
expected : 
        UltraGrid1.MouseMove - The code in the MouseMove event

**Comment by ig-ealbert** [comment]
It's likely that the cause is the space being wrapped with `<EM></EM>` tags.  There's no reason for these tags to be there.  I can either remove them in the original files, or Craig can update the parser to include spaces, even when they are italic.  Leaving it up to Craig.  If we decide to fix the content in the .xml file, Josheela can log a bug in TFS.

```
The code in the MouseMove&lt;EM&gt; &lt;/EM&gt;event
```

**Comment by craigshoemaker** [comment]
I'll take care of this in the converter. I'll have it look for spaces wrapped by other inline elements as well.
