### ISSUE TITLE
Samples section is not properly build-flagged

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#117]
Open datachart-series-highlighting.adoc in Livewire.
Observe the "samples" section at the bottom.
The Samples header and paragraph appear without build-flags, but the table is build-flagged.  In the TFS topic e4b3c0e6, the header and paragraph are also build-flagged.

```
&lt;TR style="hs-build-flags: SL"&gt;
&lt;TH style="hs-build-flags: SL"&gt;
&lt;H4&gt;Samples&lt;/H4&gt;&lt;/TH&gt;
&lt;TD style="hs-build-flags: SL"&gt;
&lt;DIV class=ig-layout-container style="hs-build-flags: SL"&gt;
&lt;P&gt;The following sample provides additional information related to this topic.&lt;/P&gt;
```

**Comment by craigshoemaker** [comment]
@ig-ealbert This is being converted correctly, the problem here is that the topic is build-flagged insanely. The original markup in TFS has build flags for (Silverlight only) applied to each row, each header and each cell. The whole table just needs to be wrapped in one SL build flag and then it will convert as you expect. Can you create a TFS issue for this, please?

**Comment by craigshoemaker** [comment]
The real culprit here is the unmapper module throwing out build flags.
