### ISSUE TITLE
Unmapped table rows displayed in one big table

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#120]
Open ig-excel-engine-list-of-supported-built-in-functions.adoc (Silverlight) in Livewire.
Compare with the online help.
http://help.infragistics.com/doc/Silverlight?page=IG_Excel_Engine_List_of_Supported_Built-in_Functions.html

There is no break between the introduction and the functions reference summary.  It all looks like one big table.

**Comment by craigshoemaker** [comment]
The reason the topic is not being converted correctly is because the table directly after the **Supported Excel Functions** heading does not have the `ig-layout` class applied.

For this topic, please create a TFS bug to have the Product Team add the CSS class.

Since automatically un-mapping topics without the right markup is not practical, any other topics not fixed like this will surface in the nested table report and we can fix them manually before going to production.

**Comment by ig-ealbert** [comment]
TFS 214418
