### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by yoshimis** [Infragistics/convertwire#126]
# The following part appear in English.

Note:
The current version of {Controls128Barcode} uses only FNC1.The control will be improved with the functions of the other special symbol characters in the next versions.

xambarcode-configuring-qr-code.ja-JP.adoc

**Comment by ig-ealbert** [comment]
@yoshimis : This is a content issue.  I will log a bug in TFS and assign it to you.

We retranslated these Barcode topics in 15.2 and this note is in English from that checkin.
$/NetAdvantage/DEV/Common/2015.2/PG/Barcodes
Changeset 544522

The reason that this shows up as translated in the online help (which confused me too) is because this shared project wasn't used in 15.2.  There was a copy of this topic in the XAML CommonControls branch that was used instead.  I think Pam and ES are setting up this project to be used now, because it's going to be shared with Windows Forms in 16.1.

FYI the actual file is "xambarcode-configuring-code128.ja-JP.adoc".
http://help.jp.infragistics.com/doc/WPF/2015.2/?page=xamBarcode_XamCode128Barcode.html

**Comment by ig-ealbert** [comment]
Bug 214405
Let me know if you want me to fix it.

**Comment by yoshimis** [comment]
Fixed.

**Comment by ig-ealbert** [comment]
@craigshoemaker or @yoshimis : Could you please close this issue?

**Comment by craigshoemaker** [comment]
Done
