### ISSUE TITLE
Some additional characters are added to xml namespaces.

### ISSUE THREAD

**Issue by gedinakova** [Infragistics/convertwire#136]
1. Load wpf\topics\xamdiagram-adding-to-a-page.adoc in Livewire
2. Scroll to "Requirements" section
3. Note the XML namespace 

Actual Result: Two "`" characters are shown at the end.
![corruptedxmlnamespace](https://cloud.githubusercontent.com/assets/16817847/14526556/ac558ace-024c-11e6-9879-ead04aba6894.png)

 Expected Result: The 2 characters should not be there.

**Comment by craigshoemaker** [comment]
This is actually converted perfectly, but the problem is that the source topic in DocumentX has too many sections of this line wrapped in the `ig-code-in-text` class. Once just the XML markup is surrounded by a single `ig-code-in-text` element, then you'll see the desired result.

I'll add this to the manual fix list

**Comment by ig-ealbert** [comment]
TFS 219336 - Fixed.
This is a result of the Word -> HTML -> Document X conversion.  Spans like the code spans will get duplicated for multiple parts of a single word or phrase that could have just 1 span.  Cleaned it up in the source file, but it will likely be a more widespread issue.

**Comment by gedinakova** [comment]
Verified
