### ISSUE TITLE
[SL] Style issues in "What's New in 2010 Volume 3" topic in Line Of Business

### ISSUE THREAD

**Issue by martotkd1** [Infragistics/convertwire#151]
1.Load SL "whats-new-in-2010-volume-3" topic in Livewire
"Related Topics" and all its links should be on separate lines for all sections in the topic

**Comment by craigshoemaker** [comment]
The conversion process does not add any formatting plain DIV elements by design. In this case **Related Topic** is contained in a plain DIV. The topic needs to be changed in DocumentX to be a heading (probably a `h2` or `h3`). After this is done the conversion will produce what you expect.

Adding to manual fix list.

**Comment by ig-ealbert** [comment]
TFS 219330 - Fixed

**Comment by martotkd1** [comment]
Verified
