### ISSUE TITLE
Missing title, broken formatting and broken table in "Sharing Color Tuning Configurations" topic.

### ISSUE THREAD

**Issue by gedinakova** [Infragistics/convertwire#173]
1. Load commoncontrols\topics\sharing-color-tuning-configuration.adoc in Livewire
2. Check the title
3. Scroll down to "Sharing Color Tuning Configurations > Preview"
4. Note the italic path "CommonApplicationData\Infragistics\Tools\ColorTuner_version\SavedThemes.xml_"
5. Scroll down to "Steps > Paste the configuration file" and check the italic path
6. Scroll to the bottom and check the table with topics

Actual Result: 
    Step 2: "Sharing Color Tuning Configuration" topic title is missing.
    Step 4: The path is "CommonApplicationData\Infragistics\Tools\ColorTuner_version\SavedThemes.xml_".
    Step 5: The path is "Environment.SpecialFolder.CommonApplicationData\Infragistics\Tools\ColorTuner_version_".
    Step 6: All table cells are shifted with one cell.

Expected Result:
    Step 2: The title should be present.
    Step 4: The path should be "CommonApplicationData\Infragistics\Tools\ColorTuner_version_\SavedThemes.xml"
    Step 5: The path should be " Environment.SpecialFolder.CommonApplicationData\Infragistics\Tools\ColorTuner_version_\".
    Step 6: Table cells should be fixed. All the "2" should not be shown.
![brokentable](https://cloud.githubusercontent.com/assets/16817847/14561642/717ab6c0-0320-11e6-8c83-6abb629389ff.png)

**Comment by craigshoemaker** [comment]
The missing title is fixed by ab4e478ed8b3695f50e74ea155322e7229d3584f

The issue with the paths/italics is because the file paths are italicized in the source document. Once these italics are removed, the conversion will work perfectly. I have added a check to the script that reports on topics to flag any topics that have underscores in the paths so we can verify they are not italicized before the final conversion.

The same is true for the table. The source HTML has a value for `colspan` and will therefore be picked up for manual processing via the tables report.

**Comment by ig-ealbert** [comment]
TFS 219337 - Fixed italicized paths by removing italic spans.

**Comment by gedinakova** [comment]
Verified all issues except the last one for the table.

**Comment by ig-ealbert** [comment]
@craigshoemaker, @gedinakova - As commented, there is a colspan on this column header.  There shouldn't be though, right???

```
                                <th colspan="2">
                                    <p>Topic</p>
                                </th>
```

http://help.infragistics.com/doc/WPF/2016.1/?page=Sharing_Color_Tuning_Configuration.html
Should I remove the colspan in the source file?  How should this be handled?
