### ISSUE TITLE
Corrupted list style in "Adding Text (xamRichTextEditor)" topic.

### ISSUE THREAD

**Issue by gedinakova** [Infragistics/convertwire#182]
1. Load commoncontrols\topics\xamrichtexteditor-managing-adding-text.adoc in Livewire
2. Scroll down to "Text content summary" section and note the style and indentation of the list

Actual Result: The items' numbering is wrong. All levels start at the same indent. There are "... ..." shown before some items.
Expected Result: The list style should be with Arabic numbers only and the indentation should reflect the item's level.
![brokenliststyle](https://cloud.githubusercontent.com/assets/16817847/14563487/e5ad8ec8-032a-11e6-8f0d-9bc2c87bd8de.png)

**Comment by craigshoemaker** [comment]
I fixed the lists to render at the correct levels, but there is another issue with this topic. AsciiDoc only supports nested lists up to five levels deep. This topic needs to be reworked in order to convey the same information without creating such a deeply nested list.

I have added this check to the reporting process so we will be notified of any other topics that have this issue.

**Comment by craigshoemaker** [comment]
closed by 4fede1e200cd82c2f005dbdb6fca30cbcd86ca4c
