### ISSUE TITLE
Issues in "Key Performance Indicators (KPIs) Visualization Overview" topic.

### ISSUE THREAD

**Issue by gedinakova** [Infragistics/convertwire#184]
1. Load commoncontrols\topics\xampivotgrid-kpis-visualization-overview1.adoc in Livewire
2. Check the table in "Required background" section
3. Check the bulleted list in "In this topic" section
4. Scroll to "Configuring KPI visualization summary chart" section
5. Check the content of each first cell in the table
6. Scroll to the bottom
7. Click "wpf" button and note the links to samples

Actual Result:
2. The table is corrupted because of the nested one
3. The first level items are not bold
5. "2" is added at the end
7. "KPI Cells" link is shown twice (in SL it's shown only once)

Expected Result:
2. One of the tables should probably be removed
3. The first level items should be bold
5. The "2" should not be present
7. "KPI Cells" link should be shown once

**Comment by craigshoemaker** [comment]
Nested tables are not supported during the conversion. This is picked up in the nested table report and needs to be processed manually after final conversion.

**Comment by gedinakova** [comment]
The issue observed in step 5 is still present.
![cellcontentissue](https://cloud.githubusercontent.com/assets/16817847/15927594/4f02449a-2e4b-11e6-8a71-5453a26a779d.png)

**Comment by ig-ealbert** [comment]
@gedinakova : As @craigshoemaker noted, this should be picked up in a tables report.  You can check for "complex" tables in the commoncontrols/tables/complex folder.  `56af539f-72e5-4bf9-8bd4-ce87561fb0e5` is included in there, because it has a colspan.  It will have to be fixed manually after the final conversion, which is why he has these reports.
