### ISSUE TITLE
datachart - creating chart in VS designer for WinForms

### ISSUE THREAD

**Issue by mddifilippo89** [Infragistics/convertwire#200]
(low priority) This topic has a build flag for android-ex, when it only needs one for WinForms only

**Comment by ig-ealbert** [comment]
The DROID_EX build flag is used in the source HTML.  It's the only build flag used in the source file.  Because of that, the build flag shows up in Livewire.

You're right - only a WinForms build flag should be needed.  This should be changed in the Document X file.  There is nothing wrong with how Livewire or Convertwire is handling this.
Submit a TFS bug and you, John, or I can fix it.

```
&lt;DIV id=Example_CS class=LanguageSpecific style="DISPLAY: block" style="hs-build-flags: DROID_EX"&gt;
```

For reference:
`<meta name="Microsoft.Help.Id" content="07e9aeae-d8bc-43ae-ae1c-e29d9c61e2bd"/>`

**Comment by craigshoemaker** [comment]
Closing this as it should be fixed in DocumentX

**Comment by ig-ealbert** [comment]
@mddifilippo89 : Can you please log this as a bug in TFS?  We don't want to lose this report.

**Comment by craigshoemaker** [comment]
@ig-ealbert that's a good idea to have the TFS task, but know also that I am tagging all these issues with the `fix-in-DocX` label so we can easily go back to them before the next conversion

**Comment by ig-ealbert** [comment]
TFS 219328 - Fixed.

**Comment by mddifilippo89** [comment]
Verified - success.
