### ISSUE TITLE
datachart - category stacked 100 column series

### ISSUE THREAD

**Issue by mddifilippo89** [Infragistics/convertwire#202]
1. VB & C# Code Snippets for everything but android are not displayed in preview area
2. Missing Silverlight build flag (if needed)
3. Refactoring build variables required

**Comment by ig-ealbert** [comment]
There is nothing Silverlight-specific in this topic so a Silverlight build-flag is not required.  It should be covered in "xaml" and "xaml-xf-ex".
The code snippets are not displayed properly for android-ex, which is what C# and VB are build-flagged as.
It looks like this div (and the VB one) are not propagating build flags to child elements.

```
&lt;DIV id=Example_CS class=LanguageSpecific style="DISPLAY: block" style="hs-build-flags: DROID_EX"&gt;
```

This is reported many times and I'll leave it up to Craig to figure out how to handle it.

**Comment by ig-ealbert** [comment]
Think I figured out what causes this.

```
ifdef::android-ex[]

*In Visual Basic:*

ifdef::win-forms[]
----

[source]
```

If you select "android-ex", you get the header, but not the code. That's because the header is flagged for "android-ex" but the code is flagged for things like "win-forms" and "xaml".
Assuming this is correct (see below), options would be to enable selecting multiple build flags in livewire at once, like toggle buttons, or to change the options to display how it would look in a certain product (ex. none of the "android-ex" or "xaml-xf-ex" options but include those build flags in a choice of "wpf" or "silverlight").
This assumes that the code is being parsed correctly, which it may not be.  For example, in this topic, I don't understand why there is an "win-forms" build flag around some of the code, because those don't exist in the source topic.  I just see the droid-ex build flags.

**Comment by craigshoemaker** [comment]
As I commented in #203, we'll update Livewire to help take care of the issue with build flags.

**Comment by mddifilippo89** [comment]
Everything is displayed correctly now but as a result build flag issues are present and known.
