### ISSUE TITLE
datachart - category step-area series

### ISSUE THREAD

**Issue by mddifilippo89** [Infragistics/convertwire#203]
1. VB & C# code snippets are not displayed in preview area for specificed platforms.
2. Refactoring required

**Comment by ig-ealbert** [comment]
Same as #202?  The code snippets not appearing even when the build-flag is chosen (DROID_EX) is the same issue.
`<DIV style="DISPLAY: block" id=Example_CS class=LanguageSpecific data-build-flags="DROID_EX">`

**Comment by craigshoemaker** [comment]
This is not a conversion issue, but rather an issue with Livewire. Right now you can only select one build flag at a time when in reality you need to apply multiple build flags to see the correct data. This is not an issue for most topics, but it is for this one. 

We are working on a new way to handle build flags in Livewire where you select the product you want to see the topic as and then it applies the appropriate build flags behind the scenes.

**Comment by mddifilippo89** [comment]
What is the status of the build flag? Do I need to do anything for bug verification?

**Comment by ig-ealbert** [comment]
@mddifilippo89 - Get the latest version of Livewire, either through the installer or through Git.  Then get the latest version of the converted topics.  Open this topic in Livewire and verify that the issue you reported is fixed by selecting the product build flag at the bottom right of Livewire.  Let me know if you have any questions about this - I can show you what to do.
https://www.yammer.com/infragistics.com/#/Threads/show?threadId=715552337
https://www.yammer.com/infragistics.com/#/Threads/show?threadId=717082745

**Comment by mddifilippo89** [comment]
Everything is displayed correctly now but as a result build flag issues are present and known.
