### ISSUE TITLE
[ta-hp] ordered list nested in unordered list

### ISSUE THREAD

**Issue by jVanZwieten** [Infragistics/convertwire#226]
//reproduce
http://help.infragistics.com/doc/TestAutomationHPWinForms/?page=Known_Issues_WinToolbarsManager.html
known-issues-wintoolbarsmanager.adoc

//result
Within the unordered list, there is an ordered list. The converted document has brought the OL out of the UL, and the UL doesn't continue after the OL, instead being prose.

//expected
The OL is embedded within one element of the UL; the UL continues on after the OL is complete.

**Comment by jVanZwieten** [comment]
manually-setting-up-windows-forms-test-automation-for-hp-software.adoc
http://help.infragistics.com/doc/TestAutomationHPWinForms/?page=Manually_Setting_Up_Windows_Forms_Test_Automation_for_HP_software.html
Another example of lists within lists not converting properly.

**Comment by jVanZwieten** [comment]
Homogeneous list types seem fine to nest as seen in:
whats-new-in-2005-volume-1.adoc
http://help.infragistics.com/doc/TestAutomationHPWinForms/?page=Whats_New_in_2005_Volume_1.html

**Comment by jVanZwieten** [comment]
In this case, the first UL in an OL chokes, while the 2nd works: 
manually-setting-up-testadvantage-for-windows-forms-(-for-ibm-rational-functional-tester-).adoc
http://help.infragistics.com/doc/TestAutomationIBMWinForms/2015.2?page=Manually_Setting_Up_TestAdvantage_for_Windows_Forms_(_for_IBM_Rational_Functional_Tester_).html

**Comment by craigshoemaker** [comment]
[List line continuation is possible with AsciiDoc](http://www.methods.co.nz/asciidoc/chunked/ch17.html#X15), however each of the lists that I looked at in this issue need some additional adjustment before they can be production ready.

For instance, one of the lists in `known-issues-wintoolbarsmanager.adoc` can be formatted correctly by adding a line with a `+` in it, but then the next list needs `[start=1]` applied to it so the list continues at the correct level.

I have added the `post-final-conversion` label to this issue so that the product team can fix these after conversion.
