### ISSUE TITLE
datachart-styling-the-chart-series.adoc tables issues.

### ISSUE THREAD

**Issue by agoldenbaum** [Infragistics/convertwire#247]
1. Sample table in "Samples" section lists Drop Shadows twice for WPF build flag.
2. In "Resources" table at the end, the DropShadowEffect Class link only shows up for WPF build flag - should exist in Silverlight too.

Extra Note:
Should the only build flag for this be Xaml-Xf-Ex? SL and WPF seem to be exactly the same for this article, and WinPhone and WinRT are essentially dead.

**Comment by ig-ealbert** [comment]
Both of the numbered items do seem like bugs in either Livewire or Convertwire.  The AsciiDoc markup has these SL build flags, but Livewire seems to display one of them for WPF (samples).  For the resources, there is a pick: statement but it doesn't seem to "pick up" silverlight.
About your note, given infinite time and resources, yes.  However, all we're doing here is converting the existing topics (with all of their outdated and confusing build flags) to asciidoc.  Going through the topics and redoing all the build flags would be a very large project.  First things first, let's get the conversion done so that anyone in the company (like you) can edit the files, not just people with a license for Document X.  In short, the confusing and outdated build flags will stay.

**Comment by craigshoemaker** [comment]
closing this as the conversion seems to be correct. I'll be updating how Livewire deals with build flags soon.

**Comment by ig-ealbert** [comment]
Yes, this looks correct in the AsciiDoc of Livewire now.  The only issue is that the sl button doesn't show the link in the Resources section.  I guess that's what you mean by "updating how Livewire deals with build flags"?

**Comment by pamelabrasil** [comment]
the build flagging in this topic was incorrect. I updated the build flags so there shouldn't be any more issues.
