### ISSUE TITLE
DROID_EX build flag not resolved correctly

### ISSUE THREAD

**Issue by pamelabrasil** [Infragistics/convertwire#262]
The DROID_EX build flag is everything except Android. However in Livewire it is resolving as ifdef::wpf,win-forms,xamarin[]. Missing SL, WINRT, WINPHONE. These platforms are not displayed, even though there are seperate ifdefs for them within in the main ifdef.
Once within the main ifdef, there is ifdef::xaml-xf-ex[], as well as seperate ifdefs for WPF, WINFORMS, XAMARIN. This causes WPF to display twice.
Example shown in radialgauge-configuring-the-scale

**Comment by pamelabrasil** [comment]
another example - datachart-category-column-series

**Comment by HUSSAR-mtrela** [comment]
@pamelabrasil 
the radialgauge-configuring-the-scale topic should be correct in docx because XAM_XF_EX is resolved to the same build flags that are also listed next to it and that is causing duplicated code blocks:

`data-build-flags="UWP,WINPHONE,WPF,SL,XAM_XF_EX,WINFORMS"`
to 
`data-build-flags="UWP,WINPHONE,WPF,SL,XAMARIN,WINFORMS"`

note that this change applies only to C# blocks and VB block are correct

**Comment by craigshoemaker** [comment]
Closing this per @HUSSAR-mtrela's comment
