### ISSUE TITLE
"Adding xamDiagram to a Page" topic: One of the steps is no longer part of the bullet list.

### ISSUE THREAD

**Issue by gedinakova** [Infragistics/convertwire#265]
1.Load wpf\topics\xamdiagram-adding-to-a-page.adoc in Livewire
2.Scroll to "3. Add the connections." section
3.Check the steps after the second XAML snippet

Actual Result: What should be step D is not part of the bullet list and is displayed as A.
Expected Result: Between C and E there should be step D with a bullet.
![stepoutofbulletlist](https://cloud.githubusercontent.com/assets/16817847/15928719/36f234e0-2e51-11e6-9599-9ea5ae60020e.png)

**Comment by craigshoemaker** [comment]
The reason the `D` is turning into an `A` is due to how AsciiDoc treats lists. The text in the file for that item just has `D.` which AsciiDoc interprets as the beginning of a new list - resulting in an `A`. 

To fix this the `D` item just needs a `DIV` wrapped around it with a list class (like the other list items) to make the content render correctly. A `DIV` like this:

`<div class="ig-level-2">`

needs to be added around the content.

**Comment by ig-ealbert** [comment]
Logged as bug 221408 and fixed.
