### ISSUE TITLE
Content issues in Data Chart > OLAP data topic

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#28]
datachart-visualizing-multi-dimensional-data-(olap-data)-(xamdatachart).ja-JP.adoc
1. Step 2.1 in the table has strange \* and _ characters.
2. #OLE_LINK20 is included in step 3.3.

**Comment by craigshoemaker** [comment]
Funny enough this is an artifact of our original topics being in Word, then converted to HTML, then put into DocumentX now being converted to AsciiDoc :stuck_out_tongue: 

Example:

```
**x*_*amDataChart*_ 
```

Will have to try and remedy with some RegEx clean up.

**Comment by ig-ealbert** [comment]
Jon from services wrote a "span cleaner" app for this purpose.
$/Documentation/Dox Utilities/SpanCleaner
I'm so happy we're getting away from the Word > HTML > DocX process.  It's not "funny enough"; this has been something known for a while and every time I suggested we don't start in Word, I was told "No, we need Word.  Anything else is too difficult".

**Comment by craigshoemaker** [comment]
Thanks for the pointer to the helper app. In the end I took a bit of a different approach. I have a clean up processes that runs on the HTML and also on the final AsciiDoc. In this instance I find all the anchor elements that are the destination of in-document links and inject some temporary content into those elements. Once that is done then it is safe to just remove any remaining empty tags.

So this commit 2515d2a8c3ba4397969d9e172a3973a2b105b8d3 closes this issue and takes care of # 2 that you noted above.

As for the first one, the bold and italic tags aren't empty, they are just unnecessary. This topic is already on the manual fix list so that will be cleaned up when we deal with the nested tables at the top of this topic.

**Comment by ig-ealbert** [comment]
Looks like I already fixed this one in TFS with TFS 210073.
