### ISSUE TITLE
Nested table is not parsed

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#41]
http://help.infragistics.com/doc/WPF/2015.2/?page=DataChart_Visualizing_Multi-Dimensional_Data_(OLAP_Data)_(xamDataChart).html
- datachart-visualizing-multi-dimensional-data-(olap-data)-(xamdatachart).adoc
- abd1333f-0efd-4fbe-8d91-710807eaa9c8

The table in the Required background section is not parsed.  This also causes the "In this Topic" section to be missed as well.

**Comment by craigshoemaker** [comment]
The problem with this doc is that it has tables nested three levels deep. The process that converts these tables automatically stops at two levels deep on purpose otherwise it would end up un-tabling data that we indeed want formatted in a tabular fashion. So this one gets to the manual fix list :smile:

**Comment by craigshoemaker** [comment]
This is fixed by 4eb0ed0380314deb22d9224e8ac19119216bc941 since I rewrote the module to deal with tables and it is a bit more flexible now.
