### ISSUE TITLE
Extra styling information is shown in the preview

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#73]
Open webdatamenu-binding-webdatamenu-to-an-xml-data-source.adoc in Livewire.
Scroll down to the first code listing.  Look right above it.

```
<style type="text/css">.csharpcode { FONT-SIZE: small; COLOR: black; FONT-FAMILY: Consolas, "Courier New", Courier, Monospace; BACKGROUND-COLOR: #ffffff } .csharpcode PRE { FONT-SIZE: small; COLOR: black; FONT-FAMILY: Consolas, "Courier New", Courier, Monospace; BACKGROUND-COLOR: #ffffff } .csharpcode PRE { MARGIN: 0em } .csharpcode .rem { COLOR: #008000 } .csharpcode .kwrd { COLOR: #0000ff } .csharpcode .str { COLOR: #006080 } .csharpcode .op { COLOR: #0000c0 } .csharpcode .preproc { COLOR: #cc6633 } .csharpcode .asp { BACKGROUND-COLOR: #ffff00 } .csharpcode .html { COLOR: #800000 } .csharpcode .attr { COLOR: #ff0000 } .csharpcode .alt { MARGIN: 0em; WIDTH: 100%; BACKGROUND-COLOR: #f4f4f4 } .csharpcode .lnum { COLOR: #606060 }</style>
```

I don't know where this comes from and it shouldn't be there, right?

**Comment by craigshoemaker** [comment]
This one is interesting. The style information isn't a part of the doc text, but rather extra CSS injected in there by DocX in order to help style the code. This is handled automatically by the Tripwire, so I am just going to update the clean up process to look for stray `style` elements and remove them.
