### ISSUE TITLE
Table does not render properly

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#82]
Open ig-excel-engine-list-of-supported-built-in-functions.adoc (Silverlight) in Livewire.
Compare with the online help.
http://help.infragistics.com/doc/Silverlight?page=IG_Excel_Engine_List_of_Supported_Built-in_Functions.html
The table with the options renders as text.  It should be a table.

**Comment by craigshoemaker** [comment]
This is a bit of an edge case. This topic is not correctly formatted in the original in that it does not include the standard CSS classes for Information Mapping. Not having those CSS classes makes it so that the unmapping module does not know how to process it.

In any event this topic includes nested tables so it will show up in the tables report and will be flagged for manual adjustment.
